### ISSUE TITLE
just a note

### ISSUE THREAD

**Issue by davephillips** [The-XOR/RackPlugins#3]
I've taken a look at your development branch (and successfully built what you've got done so far), woohoo, great stuff you're working on there ! No fear, it's not my style to make premature announcements, just wanted to drop a note of encouragement. And great thanks for the cool sequencers you've already released ! :)

**Comment by The-XOR** [comment]
Thanks for the kind words :-)
The problem with the digital branch of Rack is that you have to recompile
each module you want to use, an this leaves out the non free modules. The
idea behind this branch was to use my Launchpad; now I am taking a
different approach that works with the standard Rack ( but it is for
Windows only).

Cheers
X:

Il 30 gen 2018 16:52, "davephillips" <notifications@github.com> ha scritto:

I've taken a look at your development branch (and successfully built what
you've got done so far), woohoo, great stuff you're working on there ! No
fear, it's not my style to make premature announcements, just wanted to
drop a note of encouragement. And great thanks for the cool sequencers
you've already released ! :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/The-XOR/RackPlugins/issues/3>, or mute the thread
