### ISSUE TITLE
linux build

### ISSUE THREAD

**Issue by phdsg** [The-XOR/RackPlugins#6]
[TheXOR-0.5.5-lin.zip](https://github.com/The-XOR/RackPlugins/files/1686737/TheXOR-0.5.5-lin.zip)
SHA256: 5aef89caa072c1d1590d45c4341d872133671d977eb5163e26d591b5cf3f0c27

**Comment by The-XOR** [comment]
thanks a lot, and forgive me for the delay :-)

**Comment by phdsg** [comment]
no, thank you :)
can't wait for the next release with the spiral .
also, what happened to pattern?

**Comment by The-XOR** [comment]
spiralone in theory is finished and fully implemented, but I had not time
to do any debug so for now it is not on the master branch. I also wrote a
tiny server (only for Windows) that allow me to use my launchpads to
control the sequencers, and it is a joy :-)
Pattern sequencer (an old branch...) that I originally wrote in MAX/MSP is
very difficult to use due to the limitations of VCV interface and for now
is gone.

**Comment by phdsg** [comment]
`SHA256  TheXOR-0.5.6-lin.zip = 66c834eb2cac10a44be754b2362c92499c0026aa3126c84eae515117b34bdd4f`
[TheXOR-0.5.6-lin.zip](https://github.com/The-XOR/RackPlugins/files/1754589/TheXOR-0.5.6-lin.zip)
